schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://luxe.jahia.localhost/modules/graphql
      headers:
        user-agent: JS GraphQL
        Authorization: Basic cm9vdDpyb290MTIzNA==
        Origin: https://luxe.jahia.localhost
      introspect: true
