const NAME_OPEN = "[";
const NAME_CLOSE = "]";
const PARAMS_OPEN = "(";
const PARAMS_CLOSE = ")";
const CONDITION_OPEN = "(";
const CONDITION_CLOSE = ")";

const NODE_TYPE_OPEN = `select * from ${NAME_OPEN}`;
const NODE_TYPE_CLOSE = NAME_CLOSE;

const BELONGS_TO_SITE_OPEN = `where ISDESCENDANTNODE ${PARAMS_OPEN}'/sites/`;
const BELONGS_TO_SITE_CLOSE = `'${PARAMS_CLOSE}`;

const ADDITIONAL_CONDITION_OPEN = `and ${CONDITION_OPEN}`;
const ADDITIONAL_CONDITION_CLOSE = CONDITION_CLOSE;

export {
    NODE_TYPE_OPEN, NODE_TYPE_CLOSE,
    BELONGS_TO_SITE_OPEN, BELONGS_TO_SITE_CLOSE,
    ADDITIONAL_CONDITION_OPEN, ADDITIONAL_CONDITION_CLOSE
};