name: Nightly Test run

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 1 * * 1-5'

jobs:
  integration-tests:
    name: Integration Tests ${{ matrix.config_file }}
    strategy:
      fail-fast: false
      matrix:
        jahia_image: ["ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT"]
        config_file:
          - cypress.config-contentEditor.ts
          - cypress.config-selectorTypes.ts
          - cypress.config-jcontent.ts
          - cypress.config-menuActions.ts
          - cypress.config-pageBuilder.ts
          - cypress.config-pickers.ts
          - cypress.config-categoryManager.ts
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: jcontent
      module_branch: ${{ github.ref }}
      jahia_image: ${{ matrix.jahia_image }}
      tests_profile: ${{ matrix.config_file }}
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: jcontent-nightly-${{ matrix.config_file }}-${{ github.run_number }}
      incident_service: jcontent-${{ matrix.config_file }}
      testrail_project: jContent Module
      timeout_job: 140
      timeout_step: 90
