# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-signature:
    name: Update module signature
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jahia/jahia-modules-action/update-signature@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  static-analysis:
    name: Static Analysis (linting, vulns)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Jahia/jahia-modules-action/static-analysis@v2
        with:
          auditci_level: critical
          max_warning: 8

  unit-tests:
    name: Javascript unit tests (yarn test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: Run yarn test
        shell: bash
        run: |
          yarn
          yarn test

  build:
    name: Build Module
    needs: update-signature
    runs-on: ubuntu-latest
    env:
      NEXUS_INTERNAL_URL: ${{ secrets.NEXUS_INTERNAL_URL }}
    container:
      image: ghcr.io/jahia/jahia-docker-mvn-cache:11-jdk-noble-mvn-loaded
      credentials:
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: jahia/jahia-modules-action/build@v2
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  sonar-analysis:
    name: Sonar Analysis
    needs: build
    runs-on: ubuntu-latest
    env:
      NEXUS_INTERNAL_URL: ${{ secrets.NEXUS_INTERNAL_URL }}
    steps:
      - uses: actions/checkout@v6
      - uses: jahia/jahia-modules-action/sonar-analysis@v2
        with:
          primary_release_branch: main
          github_slug: jahia/jcontent
          github_pr_id: ${{github.event.number}}
          sonar_url: ${{ secrets.SONAR_URL }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}

  integration-tests:
    name: Integration Tests ${{ matrix.config_file }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        config_file:
          - cypress.config-contentEditor.ts
          - cypress.config-contentEditor2.ts
          - cypress.config-selectorTypes.ts
          - cypress.config-jcontent.ts
          - cypress.config-jcontent2.ts
          - cypress.config-menuActions.ts
          - cypress.config-pageBuilder.ts
          - cypress.config-pickers.ts
          - cypress.config-categoryManager.ts
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: jcontent
      module_branch: ${{ github.ref }}
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      tests_profile: ${{ matrix.config_file }}
      provisioning_manifest: provisioning-manifest-build.yml
      artifact_prefix: jcontent-${{ github.event.pull_request.number }}-${{ matrix.config_file }}
      should_skip_testrail: true
      testrail_project: jContent Module
      timeout_job: 140
      timeout_step: 90
