name: Publish tests module to NPM registry
on:
  workflow_dispatch:
    inputs:
      is_dry_run:
        description: 'DRY RUN: (SHOULD ONLY BE RUN ON NON-MAIN branch) Indicate if the workflow triggered is a dry-run of the release'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
  npm_publish:
    name: Build and publish tests module to NPM registry
    runs-on: ubuntu-latest

    steps:
      # Providing the SSH PRIVATE of a user part of an admin group
      # is necessary to bypass PR checks
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}
      # Setting up the SSH agent to be able to commit back to the repository
      # https://github.com/webfactory/ssh-agent
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Import jahia-ci GPG signing key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Setting up github configuration
        shell: bash
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "jahia-ci@jahia.com"
          git config --global user.name "jahia-ci"
      - name: Build and publish jContent test module
        shell: bash
        run: |
          cd tests
          npm get
          ls -lah

          echo; echo "Fetching dependencies..."
          yarn

          echo; echo "Building tests module..."
          yarn build

          echo; echo "Incrementing version for release.."
          npm version prerelease --preid=tests --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "[skip-ci] Cypress test module release v$NEW_VERSION"
          git tag "v$NEW_VERSION"
          git verify-commit HEAD
          git push --follow-tags

          if "${{ inputs.is_dry_run }}"; then
            if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
              echo "Dry run should be executed in non-main branch"
            else
              echo "Executing npm publish in dry-run mode"
              npm publish --access public --tag latest --dry-run
            fi
          else
            echo "Publishing jContent tests in npm..."
            npm publish --access public --tag latest
          fi
