# This workflow trigger a full Sonar analysis at regular interval
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Sonar Analysis - Scheduled

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1,3,5' # At 4AM, on Monday, Wednesday and Friday

env:
  MODULE_ID: jcontent

jobs:
  sonar-analysis:
    uses: Jahia/jahia-modules-action/.github/workflows/sonar-scan.yml@v2
    secrets: inherit
    # Keeping a matrix as it becomes useful when a maintenance branch is present.
    strategy:
      fail-fast: false
      matrix:
         git_branch: ["${{ github.event.repository.default_branch }}"]    
    with:
      module_id: jcontent
      tests_module_type: mvn
      git_branch: ${{ matrix.git_branch }}
      incident_service: jcontent-sonar
      job_container: jahia/cimg-mvn-cache:ga_cimg_openjdk_11.0.20-node
