name: Weekly Test run

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  integration-tests-standalone:
    name: Integration Tests ${{ matrix.config_file }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        jahia_image: ["jahia/jahia-ee-dev:8-SNAPSHOT"]
        config_file:
          - cypress.config-contentEditor.ts
          - cypress.config-selectorTypes.ts
          - cypress.config-jcontent.ts
          - cypress.config-menuActions.ts
          - cypress.config-pageBuilder.ts
          - cypress.config-pickers.ts
          - cypress.config-categoryManager.ts
    timeout-minutes: 120
    steps:
      - uses: jahia/jahia-modules-action/helper@v2
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/integration-tests@v2
        with:
          module_id: jcontent
          incident_service: jcontent-${{ matrix.config_file }}
          jahia_image: ${{ matrix.jahia_image }}
          jahia_cluster_enabled: true
          jahia_url: http://jahia-browsing-a:8080
          testrail_project: jContent Module
          tests_manifest: provisioning-manifest-snapshot.yml
          tests_profile: ${{ matrix.config_file }}
          should_use_build_artifacts: false
          should_skip_artifacts: true
          should_skip_notifications: false
          should_skip_testrail: false
          github_artifact_name: jcontent-nightly-${{ matrix.config_file }}-${{ github.run_number }}
          jahia_artifact_name: jcontent-nightly-${{ matrix.config_file }}-${{ github.run_number }}
          bastion_ssh_private_key: ${{ secrets.BASTION_SSH_PRIVATE_KEY_JAHIACI }}
          jahia_license: ${{ secrets.JAHIA_LICENSE_8X_FULL }}
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          testrail_username: ${{ secrets.TESTRAIL_USERNAME }}
          testrail_password: ${{ secrets.TESTRAIL_PASSWORD }}
          tests_report_name: Nightly ${{ matrix.config_file }}
          incident_pagerduty_api_key: ${{ secrets.INCIDENT_PAGERDUTY_API_KEY }}
          incident_pagerduty_reporter_email: ${{ secrets.INCIDENT_PAGERDUTY_REPORTER_EMAIL }}
          incident_pagerduty_reporter_id: ${{ secrets.INCIDENT_PAGERDUTY_REPORTER_ID }}
          incident_google_spreadsheet_id: ${{ secrets.INCIDENT_GOOGLE_SPREADSHEET_ID }}
          incident_google_client_email: ${{ secrets.INCIDENT_GOOGLE_CLIENT_EMAIL }}
          incident_google_api_key_base64: ${{ secrets.INCIDENT_GOOGLE_PRIVATE_KEY_BASE64 }}
          zencrepes_secret: ${{ secrets.ZENCREPES_WEBHOOK_SECRET }}
      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        id: test-report
        if: success() || failure()
        with:
          name: Nightly ${{ matrix.config_file }}
          path: tests/artifacts/results/xml_reports/**/*.xml
          reporter: java-junit
          fail-on-error: 'false'
          output-to: 'step-summary'
      - name: Print test report URL
        run: |
          echo "Test report URL is ${{ steps.test-report.outputs.runHtmlUrl }}"

